import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import './globals.css'
import { QueryProviders } from './components/query-providers'
import { ThemeProvider } from '@/components/ui/theme-providers'
import { ModeToggle } from '@/components/ui/mode-toogle'

const inter = Poppins({
  subsets: ['latin'],
  weight: '400',
})

export const metadata: Metadata = {
  title: 'Dolar app',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="es" suppressHydrationWarning className="antialiased">
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange>
          <div className="absolute top-4 right-4">
            <ModeToggle />
          </div>
          <QueryProviders>{children}</QueryProviders>
          <div className="flex gap-1 items-center w-full text-center justify-center pb-4 font-extralight text-sm">
            * Datos obtenidos de <span className="font-bold">DolarApi.com</span>
          </div>
        </ThemeProvider>
      </body>
    </html>
  )
}
